# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('access_token', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200)),
                ('token_last_update', models.DateField()),
                ('first_login', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
